language: node_js
node_js:
- '0.11'
before_install:
- npm install browserify -g
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
  - secure: WOo4aRWoPYp2dTsbqog8AFGjla25pj2V8n2Q1wt0YZAToff58gbW/LvYH57pU+3twZoZRLcYVebqOw29UZGgNAwOrHs+fze99fNR+3nIAQ7/7VkNVaCZ6FnGCowo2cd9/Ypp3iCPG08DwLGYGZrvEkl4QrTcEhSWRtAnEGMHdLVp2WbTlfBcqz3FkLfKsNBMvSIuVcipVcWq7ljC0N5MGv0jEwIDnunElbx5Xkv79QNMwAly0pY6NZGw+9BpsezPn318dBA47+COUHx0mdQtNjCKNs07wfLdBTFZqssie1uBsLtpM4aGbE8Jd8PjQg67b1cDGsHMAwxqh2WgJQ94D/CX5j5Ezpb039scMb8kXQp5kx2b5iCDRtXerZC+oqLqEnT7OQNxE21ZPGH4g8YHa1yM5aDjD9VT4mL+unFpSM8SJlfisqajr405UOxTT/PUhJpREZc/brzDMmJTFjldweVb/QYDPxmRSEtVddeJbGLnAAVn+Dg7U9mY2DdYunnxIEYXm8jaU58AeRSVVPV5WIXK5kDmnTeEnWBOCn83UNT26x7h7mY9/Gd5LfVgnHMT+g7t3Mr1/HBy82OTkMRqu6LM4QHc8f93VY+VNTRUp+fL0VD/bFH49Vqt/c2MjRVH2hOA/hsDVoquXNkvYA9GnULlB9O58v2eWJP8Vf46QLw=
